In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import pandas as pd
df=pd.read_csv('/content/gdrive/MyDrive/Event.csv')

In [ ]:
df.head()

Opportunity         Time  Stage               Action
0       OP001  43456.60550      1       Emailed Client
1       OP001  43466.19231      1       Emailed Client
2       OP001  43471.51592      2  Meeting with Client
3       OP001  43479.39509      3  Presented to Client
4       OP001  43483.32009      3  Presented to Client

In [ ]:
df['Event Key'] = df['Stage'].astype(str) +'-'+ df['Action']

In [ ]:
df.head(50)

Time  ...                        Event Key
Opportunity               ...                                 
OP001        43456.60550  ...                 1-Emailed Client
OP001        43466.19231  ...                 1-Emailed Client
OP001        43471.51592  ...            2-Meeting with Client
OP001        43479.39509  ...            3-Presented to Client
OP001        43483.32009  ...            3-Presented to Client
OP001        43491.23536  ...            3-Presented to Client
OP001        43492.82981  ...  4-Prepared Custom Demonstration
OP001        43496.21384  ...                   5-Prepared POC
OP001        43505.60828  ...                   5-Prepared POC
OP001        43509.59647  ...     6-Provided Pre-Sales Support
OP001        43515.23814  ...     6-Provided Pre-Sales Support
OP001        43526.02147  ...     6-Provided Pre-Sales Support
OP001        43536.79509  ...           8-Prepared Commercials
OP001        43538.67772  ...            9-Negotiation Meeting
OP001        43547.13675  ...            9-Negotiation Meeting
OP001        43555.60550  ...            11-Post Sales Support
OP001        43561.78884  ...            11-Post Sales Support
OP002        43456.60550  ...                 1-Emailed Client
OP002        43466.56731  ...            2-Meeting with Client
OP002        43474.66939  ...            2-Meeting with Client
OP002        43485.56731  ...            2-Meeting with Client
OP002        43487.45759  ...            2-Meeting with Client
OP002        43491.68259  ...  4-Prepared Custom Demonstration
OP002        43498.96453  ...  4-Prepared Custom Demonstration
OP002        43500.32981  ...  4-Prepared Custom Demonstration
OP002        43507.69300  ...                   5-Prepared POC
OP002        43510.49161  ...     6-Provided Pre-Sales Support
OP002        43515.22981  ...     6-Provided Pre-Sales Support
OP002        43522.14578  ...     6-Provided Pre-Sales Support
OP002        43530.36800  ...         7-Prepared RFP Responses
OP002        43531.42564  ...           8-Prepared Commercials
OP002        43540.14439  ...           8-Prepared Commercials
OP002        43541.94786  ...            10-Commercials Signed
OP002        43547.81731  ...            11-Post Sales Support
OP002        43550.24439  ...            11-Post Sales Support
OP002        43558.49995  ...            11-Post Sales Support
OP003        43457.60550  ...            2-Meeting with Client
OP003        43459.32356  ...            3-Presented to Client
OP003        43466.81939  ...            3-Presented to Client
OP003        43469.71661  ...            3-Presented to Client
OP003        43477.01245  ...  4-Prepared Custom Demonstration
OP003        43484.31036  ...                   5-Prepared POC
OP003        43485.41522  ...         7-Prepared RFP Responses
OP003        43495.45689  ...         7-Prepared RFP Responses
OP003        43498.46800  ...         7-Prepared RFP Responses
OP003        43500.23814  ...         7-Prepared RFP Responses
OP003        43508.60134  ...           8-Prepared Commercials
OP003        43514.86731  ...           8-Prepared Commercials
OP003        43517.92286  ...           8-Prepared Commercials
OP003        43525.77564  ...            11-Post Sales Support

[50 rows x 4 columns]

In [ ]:
events = list(df['Event Key'].unique())

In [ ]:
events = list(df['Event Key'].unique())
ev = events.pop(8)
events.append(ev)
events = ['0-Dummy'] + events

In [ ]:
events

['0-Dummy',
 '1-Emailed Client',
 '2-Meeting with Client',
 '3-Presented to Client',
 '4-Prepared Custom Demonstration',
 '5-Prepared POC',
 '6-Provided Pre-Sales Support',
 '8-Prepared Commercials',
 '9-Negotiation Meeting',
 '7-Prepared RFP Responses',
 '10-Commercials Signed',
 '11-Post Sales Support']

In [ ]:
df.head()

Opportunity         Time  Stage               Action              Event Key
0       OP001  43456.60550      1       Emailed Client       1-Emailed Client
1       OP001  43466.19231      1       Emailed Client       1-Emailed Client
2       OP001  43471.51592      2  Meeting with Client  2-Meeting with Client
3       OP001  43479.39509      3  Presented to Client  3-Presented to Client
4       OP001  43483.32009      3  Presented to Client  3-Presented to Client

In [ ]:
series_length = 5
categories = len(events)
time_steps = series_length -1

In [ ]:
df.set_index('Opportunity', inplace=True)

In [ ]:
history = []
for op in df.index:
    for x in range(len(df['Stage'].loc[op].values)-series_length):
        history.append(df['Stage'].loc[op].values[x:x+series_length])

In [ ]:
import numpy as np
np.array(history).shape

(16176, 5)

In [ ]:
history[:5]

[array([1, 1, 2, 3, 3]),
 array([1, 2, 3, 3, 3]),
 array([2, 3, 3, 3, 4]),
 array([3, 3, 3, 4, 5]),
 array([3, 3, 4, 5, 5])]

In [ ]:
from tensorflow.keras.utils import to_categorical

In [ ]:

X= np.array([row[:time_steps] for row in history])

In [ ]:

X = to_categorical(X)

In [ ]:
y=np.array([row[time_steps] for row in history])

In [ ]:
y = to_categorical(y).reshape(-1,categories)

In [ ]:
X.shape

(16176, 4, 12)

In [ ]:
y.shape

(16176, 12)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [ ]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(11323, 4, 12) (4853, 4, 12) (11323, 12) (4853, 12)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [ ]:
model = Sequential()

In [ ]:
model.add(LSTM(10, activation='relu', return_sequences=True, input_shape=(time_steps,categories)))
model.add(LSTM(10, activation='relu'))
model.add(Dense(categories, activation='softmax'))
model.compile('adam', loss='categorical_crossentropy')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 4, 10)             920       
_________________________________________________________________
lstm_1 (LSTM)                (None, 10)                840       
_________________________________________________________________
dense (Dense)                (None, 12)                132       
Total params: 1,892
Trainable params: 1,892
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X_train,y_train, epochs=10)

Epoch 1/10
354/354 [==============================] - 1s 4ms/step - loss: 1.7404
Epoch 2/10
354/354 [==============================] - 1s 4ms/step - loss: 1.1181
Epoch 3/10
354/354 [==============================] - 1s 4ms/step - loss: 1.0329
Epoch 4/10
354/354 [==============================] - 1s 4ms/step - loss: 0.9953
Epoch 5/10
354/354 [==============================] - 1s 4ms/step - loss: 0.9729
Epoch 6/10
354/354 [==============================] - 1s 4ms/step - loss: 0.9664
Epoch 7/10
354/354 [==============================] - 1s 4ms/step - loss: 0.9584
Epoch 8/10
354/354 [==============================] - 1s 4ms/step - loss: 0.9496
Epoch 9/10
354/354 [==============================] - 1s 4ms/step - loss: 0.9477
Epoch 10/10
354/354 [==============================] - 1s 4ms/step - loss: 0.9434


In [ ]:
prediction = model.predict(X_test)

In [ ]:
X_test

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.]],

       [[0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.]]], dtype=float32)

In [ ]:
events[np.argmax(prediction[1])]

'5-Prepared POC'

In [ ]:
np.argmax(y_test[1])

6

In [ ]:

np.argmax(prediction[1])

5

In [ ]:
import tensorflow as tf
from tensorflow.keras.metrics import top_k_categorical_accuracy

In [ ]:
with tf.Session() as sess:  
    print('Correct event was top prediction:', top_k_categorical_accuracy(y_test,prediction, k=1).eval())
    print('Correct event was in top two prediction:', top_k_categorical_accuracy(y_test,prediction, k=2).eval())
    print('Correct event was in top three prediction:', top_k_categorical_accuracy(y_test,prediction, k=3).eval())

AttributeError: ignored